name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        run: |
          curl -sSL https://raw.githubusercontent.com/thrackle-io/foundry/refs/heads/master/foundryup/foundryup -o $HOME/foundryup
          FOUNDRY_DIR=$HOME/foundry bash $HOME/foundryup --version $(awk '$1~/^[^#]/' script/foundryScripts/foundry.lock)
          echo "$HOME/foundry/bin" >> $GITHUB_PATH

      - name: Generate documentation
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          rm -rf docs/src/src
          forge doc
          git add .
          git commit -m "Generate documentation"
          git push
