name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest-m-16

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: |
          curl -sSL https://raw.githubusercontent.com/thrackle-io/foundry/refs/heads/master/foundryup/foundryup -o $HOME/foundryup
          FOUNDRY_DIR=$HOME/foundry bash $HOME/foundryup --version $(awk '$1~/^[^#]/' script/foundryScripts/foundry.lock)
          echo "$HOME/foundry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: Build
        run: |
          forge clean && forge build --optimize
      - name: Test
        env:
          ETHEREUM_RPC_KEY: ${{ secrets.ALCHEMY_KEY }}
          POLYGON_RPC_KEY: ${{ secrets.POLYGON_ALCHEMY_KEY }}
        run: |
          forge test --ffi
